"""Optional LLM rewriting layer for final report output."""
from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from typing import Any, Dict, Protocol

from speechpt.openai_utils import resolve_openai_api_key

logger = logging.getLogger(__name__)

DEFAULT_MODEL = "gpt-4.1-mini"
DEFAULT_BASE_URL = "https://api.openai.com/v1/responses"

SYSTEM_PROMPT = """당신은 SpeechPT의 발표 코칭 리포트 작성자입니다.
목표는 사용자가 다음 녹음에서 바로 고칠 수 있는 구체적인 발표 피드백 JSON을 작성하는 것입니다.

근거 규칙:
- 입력으로 제공된 CE/AE 분석 JSON만 근거로 작성하세요.
- CE는 슬라이드 키포인트와 발화의 정합성 신호입니다. coverage는 semantic_coverage와 keypoint_coverage를 함께 본 보수적 신호이며, 슬라이드 내용을 모두 설명했는지 채점하는 새 축으로 확장하지 마세요.
- AE는 발화 속도, 침묵, dwell, 간투사, pitch/energy 변화 신호입니다. 인성/능력/성실성 같은 추정은 금지합니다.
- VLM/visual/likely_keywords 계열 신호가 있더라도 사용자에게 "말했어야 할 정답 키워드"처럼 단정하지 마세요.
- alignment.warnings 또는 confidence가 낮으면 정렬이 불확실하다는 점을 반영해 단정적인 표현을 줄이세요.

작성 규칙:
- 모든 문장은 한국어 존댓말로 작성하세요.
- 추상적인 표현만 쓰지 말고, 가능한 경우 입력 JSON의 수치나 슬라이드 번호를 근거로 포함하세요.
- "좋습니다", "보완하세요"처럼 단독으로 끝나는 일반론은 금지합니다.
- 개선 액션은 사용자가 실제로 따라 할 수 있는 행동으로 쓰세요. 예: "슬라이드 3 시작 시 핵심 용어를 한 문장으로 먼저 말하세요."
- 전체 평가는 2~3문장 이내로 하되, 주요 원인과 우선순위를 포함하세요.
- 강점은 실제 입력 근거가 있는 경우에만 작성하세요. 근거가 약하면 "상대적으로 안정적인 부분"처럼 제한적으로 표현하세요.
- slide_comments는 문제가 큰 슬라이드 위주로 작성하고, 각 comment는 1문장으로 제한하세요.
- 반드시 JSON 객체만 출력하세요. 코드블록, 설명, 마크다운을 출력하지 마세요."""

USER_PROMPT = """아래 SpeechPT 분석 결과를 사용자에게 보여줄 최종 코멘트로 요약하세요.

출력 품질 기준:
- overall_comment: 전체 점수, alignment warning/confidence, 가장 큰 개선 우선순위를 2~3문장으로 요약
- strengths: 실제 근거가 있는 강점 1~2개. 없으면 억지로 만들지 말고 빈 배열 허용
- priority_actions: 우선순위 높은 개선 행동 3개. 각 항목은 "무엇을/어디서/어떻게"가 드러나야 함
- slide_comments: highlight_sections 또는 per_slide_detail에서 문제가 큰 슬라이드만 선택. 각 슬라이드는 가장 중요한 피드백 1문장

표현 금지:
- "전반적으로 좋습니다", "더 자세히 설명하세요", "명확히 전달하세요"처럼 근거 없는 추상문
- 입력 JSON에 없는 새 점수, 새 평가축, 슬라이드 충실도/누락 주제 채점
- 사용자에게 VLM caption, likely_keywords_in_speech, 내부 alignment 신호명을 그대로 노출

출력 JSON 형식:
{{
  "overall_comment": "전체 발표에 대한 2~3문장 요약. 수치나 주요 근거를 포함.",
  "strengths": ["근거가 있는 잘한 점 1", "근거가 있는 잘한 점 2"],
  "priority_actions": ["구체적 개선 액션 1", "구체적 개선 액션 2", "구체적 개선 액션 3"],
  "slide_comments": [
    {{"slide_id": 1, "comment": "해당 슬라이드에서 가장 중요한 피드백 1문장. 가능하면 수치/누락 유형/말하기 행동 포함."}}
  ]
}}

분석 JSON:
{report_json}
"""


class TextGenerationClient(Protocol):
    def generate_json(self, *, system_prompt: str, user_prompt: str, model: str, max_output_tokens: int) -> Dict[str, Any]:
        """Return a parsed JSON object generated by the model."""


class OpenAIResponsesTextClient:
    """Minimal stdlib OpenAI Responses client for text-only JSON output."""

    def __init__(self, api_key: str, base_url: str = DEFAULT_BASE_URL, timeout_sec: float = 60.0):
        if not api_key:
            raise ValueError("OpenAI API key is required for LLM report generation.")
        self.api_key = api_key
        self.base_url = base_url
        self.timeout_sec = timeout_sec

    def generate_json(self, *, system_prompt: str, user_prompt: str, model: str, max_output_tokens: int) -> Dict[str, Any]:
        payload = {
            "model": model,
            "input": [
                {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
                {"role": "user", "content": [{"type": "input_text", "text": user_prompt}]},
            ],
            "temperature": 0,
            "max_output_tokens": max_output_tokens,
            "text": {"format": {"type": "json_object"}},
        }
        return _parse_json_object(self._request(payload))

    def _request(self, payload: Dict[str, Any]) -> str:
        body = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            self.base_url,
            data=body,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_sec) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail_text = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"OpenAI report request failed: {exc.code} {detail_text}") from exc
        return _extract_response_text(response_payload)


def _extract_response_text(payload: Dict[str, Any]) -> str:
    if isinstance(payload.get("output_text"), str):
        return payload["output_text"]
    parts = []
    for item in payload.get("output", []):
        if not isinstance(item, dict):
            continue
        for content in item.get("content", []):
            if isinstance(content, dict) and isinstance(content.get("text"), str):
                parts.append(content["text"])
    return "\n".join(parts).strip()


def _parse_json_object(text: str) -> Dict[str, Any]:
    payload = json.loads(text.strip())
    if not isinstance(payload, dict):
        raise ValueError("LLM report response JSON must be an object.")
    return payload


def _compact_report(report: Dict[str, Any], max_slides: int = 12) -> Dict[str, Any]:
    return {
        "overall_scores": report.get("overall_scores", {}),
        "global_summary": report.get("global_summary", {}),
        "highlight_sections": report.get("highlight_sections", [])[:max_slides],
        "per_slide_detail": report.get("per_slide_detail", [])[:max_slides],
        "alignment": {
            key: report.get("alignment", {}).get(key)
            for key in ("mode", "strategy_used", "confidence", "warnings")
            if key in report.get("alignment", {})
        },
    }


def build_llm_feedback(
    report: Dict[str, Any],
    config: Dict[str, Any] | None = None,
    client: TextGenerationClient | None = None,
) -> Dict[str, Any] | None:
    """Generate optional final LLM feedback. Returns None on disabled/fallback."""
    cfg = config or {}
    if not cfg.get("enabled", False):
        return None
    resolved_client = client
    if resolved_client is None:
        api_key = resolve_openai_api_key(cfg)
        if not api_key:
            logger.warning("LLM report enabled but OpenAI API key is not configured; skipping LLM output.")
            return None
        resolved_client = OpenAIResponsesTextClient(
            api_key=api_key,
            base_url=str(cfg.get("base_url", DEFAULT_BASE_URL)),
            timeout_sec=float(cfg.get("timeout_sec", 60.0)),
        )

    compact = _compact_report(report, max_slides=int(cfg.get("max_slides", 12)))
    user_prompt = USER_PROMPT.format(report_json=json.dumps(compact, ensure_ascii=False, indent=2))
    try:
        return resolved_client.generate_json(
            system_prompt=str(cfg.get("system_prompt", SYSTEM_PROMPT)),
            user_prompt=user_prompt,
            model=str(cfg.get("model", DEFAULT_MODEL)),
            max_output_tokens=int(cfg.get("max_output_tokens", 1200)),
        )
    except Exception:
        logger.exception("LLM report generation failed; returning deterministic report only.")
        return None
