"""Optional LLM rewriting layer for final report output."""
from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from typing import Any, Dict, Protocol

from speechpt.openai_utils import resolve_openai_api_key

logger = logging.getLogger(__name__)

DEFAULT_MODEL = "gpt-4.1-mini"
DEFAULT_BASE_URL = "https://api.openai.com/v1/responses"

SYSTEM_PROMPT = """당신은 SpeechPT의 발표 코칭 리포트 작성자입니다.
입력으로 제공된 CE/AE 분석 JSON만 근거로 한국어 피드백을 작성하세요.
새 평가 축, 새 점수, 슬라이드 충실도/누락 주제 평가는 만들지 마세요.
과장하지 말고, 사용자가 다음 발표 연습에서 바로 고칠 수 있는 표현으로 작성하세요.
반드시 JSON 객체만 출력하세요."""

USER_PROMPT = """아래 SpeechPT 분석 결과를 사용자에게 보여줄 최종 코멘트로 요약하세요.

출력 JSON 형식:
{{
  "overall_comment": "전체 발표에 대한 2~3문장 요약",
  "strengths": ["잘한 점 1", "잘한 점 2"],
  "priority_actions": ["우선 개선 액션 1", "우선 개선 액션 2", "우선 개선 액션 3"],
  "slide_comments": [
    {{"slide_id": 1, "comment": "해당 슬라이드에서 가장 중요한 피드백 1문장"}}
  ]
}}

분석 JSON:
{report_json}
"""


class TextGenerationClient(Protocol):
    def generate_json(self, *, system_prompt: str, user_prompt: str, model: str, max_output_tokens: int) -> Dict[str, Any]:
        """Return a parsed JSON object generated by the model."""


class OpenAIResponsesTextClient:
    """Minimal stdlib OpenAI Responses client for text-only JSON output."""

    def __init__(self, api_key: str, base_url: str = DEFAULT_BASE_URL, timeout_sec: float = 60.0):
        if not api_key:
            raise ValueError("OpenAI API key is required for LLM report generation.")
        self.api_key = api_key
        self.base_url = base_url
        self.timeout_sec = timeout_sec

    def generate_json(self, *, system_prompt: str, user_prompt: str, model: str, max_output_tokens: int) -> Dict[str, Any]:
        payload = {
            "model": model,
            "input": [
                {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
                {"role": "user", "content": [{"type": "input_text", "text": user_prompt}]},
            ],
            "temperature": 0,
            "max_output_tokens": max_output_tokens,
            "text": {"format": {"type": "json_object"}},
        }
        return _parse_json_object(self._request(payload))

    def _request(self, payload: Dict[str, Any]) -> str:
        body = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            self.base_url,
            data=body,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_sec) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail_text = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"OpenAI report request failed: {exc.code} {detail_text}") from exc
        return _extract_response_text(response_payload)


def _extract_response_text(payload: Dict[str, Any]) -> str:
    if isinstance(payload.get("output_text"), str):
        return payload["output_text"]
    parts = []
    for item in payload.get("output", []):
        if not isinstance(item, dict):
            continue
        for content in item.get("content", []):
            if isinstance(content, dict) and isinstance(content.get("text"), str):
                parts.append(content["text"])
    return "\n".join(parts).strip()


def _parse_json_object(text: str) -> Dict[str, Any]:
    payload = json.loads(text.strip())
    if not isinstance(payload, dict):
        raise ValueError("LLM report response JSON must be an object.")
    return payload


def _compact_report(report: Dict[str, Any], max_slides: int = 12) -> Dict[str, Any]:
    return {
        "overall_scores": report.get("overall_scores", {}),
        "global_summary": report.get("global_summary", {}),
        "highlight_sections": report.get("highlight_sections", [])[:max_slides],
        "per_slide_detail": report.get("per_slide_detail", [])[:max_slides],
        "alignment": {
            key: report.get("alignment", {}).get(key)
            for key in ("mode", "strategy_used", "confidence", "warnings")
            if key in report.get("alignment", {})
        },
    }


def build_llm_feedback(
    report: Dict[str, Any],
    config: Dict[str, Any] | None = None,
    client: TextGenerationClient | None = None,
) -> Dict[str, Any] | None:
    """Generate optional final LLM feedback. Returns None on disabled/fallback."""
    cfg = config or {}
    if not cfg.get("enabled", False):
        return None
    resolved_client = client
    if resolved_client is None:
        api_key = resolve_openai_api_key(cfg)
        if not api_key:
            logger.warning("LLM report enabled but OpenAI API key is not configured; skipping LLM output.")
            return None
        resolved_client = OpenAIResponsesTextClient(
            api_key=api_key,
            base_url=str(cfg.get("base_url", DEFAULT_BASE_URL)),
            timeout_sec=float(cfg.get("timeout_sec", 60.0)),
        )

    compact = _compact_report(report, max_slides=int(cfg.get("max_slides", 12)))
    user_prompt = USER_PROMPT.format(report_json=json.dumps(compact, ensure_ascii=False, indent=2))
    try:
        return resolved_client.generate_json(
            system_prompt=str(cfg.get("system_prompt", SYSTEM_PROMPT)),
            user_prompt=user_prompt,
            model=str(cfg.get("model", DEFAULT_MODEL)),
            max_output_tokens=int(cfg.get("max_output_tokens", 1200)),
        )
    except Exception:
        logger.exception("LLM report generation failed; returning deterministic report only.")
        return None
